  // tslint:disable: max-line-length
export const PATCH_TABLE = [
    {num: 0 , descrip: '“#1 Worker”'},
    {num: 1 , descrip: 'Security Guard patch'},
    {num: 2 , descrip: 'Blood Type (Reference Patch)'},
    {num: 3 , descrip: 'Red Shirt Logo'},
    {num: 4 , descrip: '“Don’t Run You’ll Only Die Tired” Backpatch'},
    {num: 5 , descrip: 'Poker Hand: Dead Mans Hand (Aces full of 8s)'},
    {num: 6 , descrip: 'Biohazard Symbol'},
    {num: 7 , descrip: 'Mr. Yuck'},
    {num: 8 , descrip: 'Nuclear Symbol'},
    {num: 9 , descrip: '“Eat The Rich”'},
    {num: 10, descrip: ' “Be Sure: Doubletap”'},
    {num: 11, descrip: ' Flame Emoji'},
    {num: 12, descrip: ' Smiley Face (Glow in the Dark)'},
    {num: 13, descrip: ' “Smile: Big Brother is Watching”'},
    {num: 14, descrip: ' Jolly Roger'},
    {num: 15, descrip: ' Viking Skull'},
    {num: 16, descrip: ' “APEX PREDATOR” (Sabertooth Skull)'},
    {num: 17, descrip: ' Pin-Up (Ace of Spades)'},
    {num: 18, descrip: ' Queen of Hearts'},
    {num: 19, descrip: ' Pin-Up (Mechanic)'},
    {num: 20, descrip: ' BOHICA (Bend Over Here It Comes)'},
    {num: 21, descrip: ' Front Towards Enemy (Claymore Mine)'},
    {num: 22, descrip: ' Pin-Up (Riding Missile)'},
    {num: 23, descrip: ' FUBAR'},
    {num: 24, descrip: ' “I’m A (Love) Machine”'},
    {num: 25, descrip: ' Medic Patch (Skull and Crossbones on Logo)'},
    {num: 26, descrip: ' HELLO MY NAME IS:'},
    {num: 27, descrip: ' “Powered By Coffee”'},
    {num: 28, descrip: ' “Take Me To Your Leader” (UFO)'},
    {num: 29, descrip: ' “DO YOUR JOB”'},
    {num: 30, descrip: ' “Take My Life (Please)”'},
    {num: 31, descrip: ' “All Out of Fucks To Give” (Astronaut with Turned Out Pockets)'},
    {num: 32, descrip: ' Allergic To Bullshit (Medical Style Patch)'},
    {num: 33,  descrip: '“Fix Me First” (Caduceus)'},
    {num: 34,  descrip: '“Upstanding Citizen”'},
    {num: 35,  descrip: 'NASA Logo'},
    {num: 36,  descrip: '“Cowboy Up” (Crossed Revolvers)'},
    {num: 37,  descrip: 'Dove in Crosshairs'},
    {num: 38,  descrip: 'Chibi Cthulhu'},
    {num: 39,  descrip: '“Welcome to the DANGER ZONE”'},
    {num: 40,  descrip: 'Skull and Crossed Wrenches'},
    {num: 41,  descrip: 'Pin-Up (Succubus)'},
    {num: 42,  descrip: '“DILLIGAF?”'},
    {num: 43,  descrip: '“DRINK / FIGHT / FUCK”'},
    {num: 44,  descrip: '“Work Hard / Party Harder”'},
    {num: 45,  descrip: 'Mudflap Girl'},
    {num: 46,  descrip: 'Fun Meter (reading: bad time)'},
    {num: 47,  descrip: '“GAME OVER” (Bride & Groom)'},
    {num: 48,  descrip: 'Heart'},
    {num: 49,  descrip: '“IMPROVE / ADAPT / OVERCOME”'},
    {num: 50,  descrip: '“SUCK IT UP”'},
    {num: 51,  descrip: 'HMFIC (Head Mother Fucker In Charge)'},
    {num: 52,  descrip: '“Troubleshooter”'},
    {num: 53,  descrip: '“IF I’M RUNNING KEEP UP” Backpatch'},
    {num: 54,  descrip: 'Crossed Hammers with Wings'},
    {num: 55,  descrip: '“Keep Well Lubricated”'},
    {num: 56,  descrip: 'Soviet Hammer & Sickle'},
    {num: 57,  descrip: '“Plays Well With Others”'},
    {num: 58,  descrip: '“Live Free and Die”'},
    {num: 59,  descrip: 'Pin-Up (Nurse): “The Louder You Scream the Faster I Come”'},
    {num: 60,  descrip: '“Meat Bag”'},
    {num: 61,  descrip: '“I Am Not A Robot”'},
    {num: 62,  descrip: 'Red Gear'},
    {num: 63,  descrip: '“I Can’t Fix Stupid”'},
    {num: 64,  descrip: '“Space IS My Home” (Sad Astronaut)'},
    {num: 65,  descrip: 'All Seeing Eye'},
    {num: 66,  descrip: '“Do I LOOK Like An Expert”'},
    {num: 67, descrip: '“NOMAD”'},
    {num: 68, descrip: '“I’m Not A Rocket Scientist / But You’re An Idiot”'},
    {num: 69, descrip: '“LONER”'},
    {num: 70, descrip: '“I Am My Brothers Keeper”'},
    {num: 71, descrip: '“Mama Tried”'},
    {num: 72, descrip: 'Black Widow Spider'},
    {num: 73, descrip: '“My Other Ride Married You”'},
    {num: 74, descrip: '“One Size Fits All” (Grenade)'},
    {num: 75, descrip: 'Grim Reaper Backpatch'},
    {num: 76, descrip: 'трахаться (Get Fucked, Russian)'},
    {num: 77, descrip: '“Smooth Operator”'},
    {num: 78, descrip: 'Atom Symbol'},
    {num: 79, descrip: '“For Science!”'},
    {num: 80, descrip: '“Actually, I Am A Rocket Scientist”'},
    {num: 81, descrip: '“Help Wanted”'},
    {num: 82, descrip: 'Princess'},
    {num: 83, descrip: '“I Like My Tools Clean / And My Lovers Dirty”'},
    {num: 84, descrip: '“GOOD BOY”'},
    {num: 85, descrip: 'Dice (Snake Eyes)'},
    {num: 86, descrip: '“Travel To Distant Exotic Places / Meet Unusual Things / Get Eaten”'},
    {num: 87, descrip: '“Good” (Brain)'},
    {num: 88, descrip: '“Bad Bitch”'},
    {num: 89, descrip: '“Too Pretty To Die”'},
    {num: 90, descrip: '“Fuck Forever” (Roses)'},
    {num: 91, descrip: 'Icarus'},
    {num: 92, descrip: '”Girls Best Friend” (Diamond)'},
    {num: 93, descrip: 'Risk of Electrocution Symbol'},
    {num: 94, descrip: 'Inverted Cross'},
    {num: 95, descrip: '“Do You Sign My Paychecks?” Backpatch'},
    {num: 96, descrip: '“I ♥ Myself”'},
    {num: 97, descrip: 'Double Cherry'},
    {num: 98, descrip: '“Volunteer”'},
    {num: 99, descrip: '“Solve Et Coagula” (Baphomet)'},
  ];
export const TRINKET_TABLE = [
    { num: 0, descrip: 'Preserved Insectile Aberration'},
    { num: 1, descrip: 'Faded Green Poker Chip'},
    { num: 2, descrip: 'Antique Company Script (Asteroid Mine)'},
    { num: 3, descrip: 'Dessicated Husk Doll'},
    { num: 4, descrip: 'Alien Pressed Flower (common)'},
    { num: 5, descrip: 'Necklace of Shell Casings'},
    { num: 6, descrip: 'Corroded Android Logic Core'},
    { num: 7, descrip: 'Pamphlet: Signs of Parasitical Infection'},
    { num: 8, descrip: 'Manual: Treat Your Rifle Like A Lady'},
    { num: 9, descrip: 'Bone Knife'},
    { num: 10, descrip: 'Calendar: Alien Pin-Up Art'},
    { num: 11, descrip: 'Dog Tags (Heirloom)'},
    { num: 12, descrip: 'Holographic Serpentine Dancer'},
    { num: 13, descrip: 'Snake Whiskey'},
    { num: 14, descrip: 'Medical Container, Purple Powder'},
    { num: 15, descrip: 'Pills: Male Enhancement, Shoddy'},
    { num: 16, descrip: 'Casino Playing Cards'},
    { num: 17, descrip: 'Lagomorph Foot'},
    { num: 18, descrip: 'Moonstone Ring'},
    { num: 19, descrip: 'Manual: Mining Safety and You'},
    { num: 20, descrip: 'Pamphlet: Against Human Simulacrum'},
    { num: 21, descrip: 'Animal Skull, 3 Eyes, Curled Horns'},
    { num: 22, descrip: 'Bartender’s Certification (Expired)'},
    { num: 23, descrip: 'Bent Wrench'},
    { num: 24, descrip: 'Prospecting Mug, Dented'},
    { num: 25, descrip: 'Eerie Mask'},
    { num: 26, descrip: 'Vantablack Marble'},
    { num: 27, descrip: 'Ivory Dice'},
    { num: 28, descrip: 'Tarot Cards, Worn, Pyrite Gilded edges'},
    { num: 29, descrip: 'Bag of Assorted Teeth'},
    { num: 30, descrip: 'Ashes (A Relative)'},
    { num: 31, descrip: 'DNR Beacon Necklace'},
    { num: 32, descrip: 'Cigarettes (Grinning Skull)'},
    { num: 33, descrip: 'Pills: Areca Nut'},
    { num: 34, descrip: 'Rejected Application (Colony Ship)'},
    { num: 35, descrip: 'Pamphlet: Android Overlords'},
    { num: 36, descrip: 'Smut (Seditious): The Captain, Ordered'},
    { num: 37, descrip: 'Key (Childhood Home)'},
    { num: 38, descrip: 'Manual: Panic: Harbinger of Catastrophe'},
    { num: 39, descrip: 'Token: “Is Your Morale Improving?”'},
    { num: 40, descrip: 'Phosphorescent Sticks, Neon'},
    { num: 41, descrip: 'Pamphlet: The Indifferent Stars'},
    { num: 42, descrip: 'Calendar: Military Battles'},
    { num: 43, descrip: 'Manual: Rich Captain, Poor Captain'},
    { num: 44, descrip: 'Campaign Poster (Home Planet)'},
    { num: 45, descrip: 'Pendant: Shell Fragments Suspended in Plastic'},
    { num: 46, descrip: 'Titanium Toothpick'},
    { num: 47, descrip: 'Gloves, Leather (Xenomorph Hide)'},
    { num: 48, descrip: 'Pamphlet: Zen and the Art of Cargo Arrangement'},
    { num: 49, descrip: 'Pictorial Pornography, Dogeared, Well Thumbed'},
    { num: 50, descrip: 'Brass Knuckles'},
    { num: 51, descrip: 'Fuzzy Handcuffs'},
    { num: 52, descrip: 'Journal of Grudges'},
    { num: 53, descrip: 'Stylized Cigarette Case'},
    { num: 54, descrip: 'Ball of Assorted Gauge Wire'},
    { num: 55, descrip: 'Spanner'},
    { num: 56, descrip: 'Switchblade, Ornamental'},
    { num: 57, descrip: 'Powdered Xenomorph Horn'},
    { num: 58, descrip: 'Bonsai Tree'},
    { num: 59, descrip: 'Golf Club (Putter)'},
    { num: 60, descrip: 'Trilobite Fossil'},
    { num: 61, descrip: 'Pamphlet: A Girl In Every Port'},
    { num: 62, descrip: 'Patched Overalls, Personalized'},
    { num: 63, descrip: 'Fleshy Thing Sealed in a Murky Jar'},
    { num: 64, descrip: 'Spiked Bracelet'},
    { num: 65, descrip: 'Harmonica'},
    { num: 66, descrip: 'Manual: Spacefarer\'s Almanac'},
    { num: 67, descrip: 'Faded Photograph, A Windswept Heath'},
    { num: 68, descrip: 'Stress Ball reads: Zero Stress in Zero G'},
    { num: 69, descrip: 'Manual: Moonshining With Gun Oil & Fuel'},
    { num: 70, descrip: 'Gyroscope, Bent, Tin'},
    { num: 71, descrip: 'Coffee Cup, Chipped, HAPPINESS IS MANDATORY'},
    { num: 72, descrip: 'Darts, Magnetic'},
    { num: 73, descrip: 'Spray Paint'},
    { num: 74, descrip: 'Wanted Poster, Weathered'},
    { num: 75, descrip: 'Locket, Hair Braid'},
    { num: 76, descrip: 'Pick, Miniature'},
    { num: 77, descrip: 'Blanket, Fire Retardant'},
    { num: 78, descrip: 'Hooded Parka, Fleece-Lined'},
    { num: 79, descrip: 'BB Gun'},
    { num: 80, descrip: 'Flint Hatchet'},
    { num: 81, descrip: 'Pendant: Two Astronauts form a Skull'},
    { num: 82, descrip: 'Rubik\'s Cube'},
    { num: 83, descrip: 'Manual: Survival: Eat Soup With a Knife'},
    { num: 84, descrip: 'Sputnik Pin'},
    { num: 85, descrip: 'Ushanka'},
    { num: 86, descrip: 'Trucker Cap, Mesh, Grey Alien Logo'},
    { num: 87, descrip: 'Menthol Balm'},
    { num: 88, descrip: 'Pith Helmet'},
    { num: 89, descrip: '10x10 Tarp'},
    { num: 90, descrip: 'I Ching, Missing Sticks'},
    { num: 91, descrip: 'Kukri'},
    { num: 92, descrip: 'Trench Shovel'},
    { num: 93, descrip: 'Shiv, Sharpened Butter Knife'},
    { num: 94, descrip: 'Taxidermied Cat'},
    { num: 95, descrip: 'Pamphlet: Interpreting Sheep Dreams'},
    { num: 96, descrip: 'Pair of Shot Glasses, Spent Shotgun Shells'},
    { num: 97, descrip: 'Opera Glasses'},
    { num: 98, descrip: 'Pamphlet: The Relic of Flesh'},
    { num: 99, descrip: 'Miniature Chess Set, Bone, Pieces Missing'},
  ];

export const FIRST_NAMES = [
  'MALACHI',
  'LUKE',
  'CORTEZ',
  'RAY',
  'DASHIELL',
  'NADIA',
  'DONATELLA',
  'KARL',
  'SONYA',
  ' KLAUS',
  ' NICOLE',
  ' HANNA',
  ' WANG XIU',
  ' LI',
  ' KUKI',
  ' MERCY',
  ' JESSE',
  ' BILAL',
  ' HECTOR',
  ' GAMBIO',
  ' SELENA',
  ' AMIR',
  ' YOUSEF',
  ' KHALIL',
  ' OTGONBAYAR',
  ' BATBAYAR',
  ' ANTONIA',
  ' JULIANA',
  ' MARCIA',
  ' EVANDER',
  ' ESTELLE',
  ' DUTCH',
  ' SADIE',
  ' LUCKY',
  ' DARREN',
  ' SINEAD',
  ' ELLIS',
  ' WILLIAM',
  ' ENOCH',
  ' URIEL',
  ' SCOTT',
  ' AMBROSE',
  ' RACHEL',
  ' ASHER',
  ' HAING',
  ' SOMETH',
  ' HAXHI',
  ' GRISELDA',
  ' CHINO',
  ' CLAUDIA',
  ' JOHNNY',
  ' ROY',
  ' AUDRINA',
  ' RACHEL',
  ' STELLA',
  ' PETER',
  ' LOUIS',
  ' DUTCH',
  ' JOEY',
  ' ILSE',
  ' MINAL',
  ' FALAK',
  ' JASPER',
  ' YASUKO',
  ' RUMI',
  ' MINAMI',
  ' LEMON',
  ' AIKO',
  ' MUNROE',
  ' ZELAG',
  ' MURAT',
  ' GUNNEL',
  ' SARAH',
  ' KJELL',
  ' VILGOT',
  ' BORJE',
  ' PELLE',
  ' MAI',
  ' STOFFE',
  ' SYLVIE',
  ' ALEXIS',
  ' MED',
  ' JÉRÔME',
  ' BERNTH',
  ' ODAFIN',
  ' SELDEN',
  ' NGUGI',
  ' NRIPEN',
  ' GAUR',
  ' ARVIND',
  ' FRANCES',
  ' MAGDALENA',
  ' MARCUS',
  ' ALAISTAIR',
  ' CHUCK',
  ' JONESY',
  ' MARSHALL',
  ' CARTER',
  ' JACKSON',
   'KHANH',
];

export const LAST_NAMES = [
  'REX',
  'HONEY',
  'CASTRO',
  'HAMMETT',
  'CHANCELLOR',
  'FEDEROV',
  'LANGERFELD',
  'NADEAU',
  'BERLIN',
  'SINGH',
  'VASSILLY',
  'KOLLONTAI',
  'YING',
  'WEI',
  'SYNOVATE',
  'CHIVERS',
  'BELL',
  'SAID',
  'RIOS',
  'BONANNO',
  'GARCIA',
  'RAJA',
  'TENGKU',
  'WAN',
  'SEPP',
  'REBANE',
  'HUSEYNOVA',
  'MAMMADOVA',
  'ALIYEV',
  'TYSON',
  'KING',
  'SCHULTZ',
  'ROTH',
  'LUCIANO',
  'HATCH',
  'GOTHBESHIRE',
  'HARLAN',
  'STANIFORTH',
  'DONAHUE',
  'LEWIS',
  'BERLIN',
  'CARVER',
  'LOCARD',
  'MARSTON',
  'BOUILLEVAUX',
  'UNG',
  'BIÇAKÇIU',
  'BLANCO',
  'ÁNTRAX',
  'OCHOA',
  'AJAR',
  'LOPEZ',
  'PATRIDGE',
  'BILSON',
  'BROUSSARD',
  'BUDAJ',
  'WEINBERG',
  'SCHULTZ',
  'NOE',
  'VON KLAPPER',
  'ARORA',
  'ALI',
  'SHARP',
  'TAKAHASHI',
  'KIMATA',
  'AOYAMA',
  'HANAZAWA',
  'FUKUI',
  'BERGDORF',
  'GOODMAN',
  'AUBERJONOIS',
  'THULIN',
  'GIERCKSKY',
  'PINK',
  'SJOMAN',
  'NYMAN',
  'LINDBERG',
  'ZETTERLING',
  'LILJEDAHL',
  'DENIS',
  'DIAMENT',
  'TEYNAC',
  'FANDOR',
  'TUTUOLA',
  'OBIECHINA',
  'WEST',
  'LO LIYONG',
  'CHAKRABORTY',
  'VENUGOPAL',
  'JI',
  'FARMER',
  'GAGARINA',
  'DALY',
  'RABBITT',
  'DELILLO',
  'DIOSDADO',
  'LYNCH',
  'HARRISON',
  'DUKES',
  'LAO',
];

export const SKILLS = [
  {title: 'Archaeology', percent: '10%', cost: 1, pre: [], descrip: 'Ancient cultures and their artifacts'},
  {title: 'Art', percent: '10%', cost: 1, pre: [], descrip: ' The expression or application of a species’ creative ability and imagination'},
  {title: 'Athletics', percent: '10%', cost: 1, pre: [], descrip: ' Physical sports and games'},
  {title: 'Biology', percent: '10%', cost: 1, pre: [], descrip: ' Study of life'},
  {title: 'Chemistry', percent: '10%', cost: 1, pre: [], descrip: ' The identification of the substances of which matter is composed'},
  {title: 'Computers', percent: '10%', cost: 1, pre: [], descrip: ' Fluent use of computers and networks'},
  {title: 'Driving', percent: '10%', cost: 1, pre: [], descrip: ' Operation and control of motor vehicles'},
  {title: 'First Aid', percent: '10%', cost: 1, pre: [], descrip: ' Emergency medical care and treatment'},
  {title: 'Geology', percent: '10%', cost: 1, pre: [], descrip: ' The solid features of any terrestrial planet or natural satellite'},
  {title: 'Heavy Machinery', percent: '10%', cost: 1, pre: [], descrip: ' Operation and use of large pieces of equipment (cranes, exosuits, forklifts, etc.)'},
  {title: 'Hydroponics', percent: '10%', cost: 1, pre: [], descrip: ' Growing plants in nutrient solutions without soil (farming in space)'},
  {title: 'Linguistics', percent: '10%', cost: 1, pre: [], descrip: ' Study of language'},
  {title: 'Mathematics', percent: '10%', cost: 1, pre: [], descrip: ' The science of numbers, quantity, and space.'},
  {title: 'Mechanical Repair', percent: '10%', cost: 1, pre: [], descrip: ' Fixing broken machines'},
  {title: 'Military Training', percent: '10%', cost: 1, pre: [], descrip: ' Standard basic training given to all military personnel'},
  {title: 'Piloting', percent: '10%', cost: 1, pre: [], descrip: ' Operation and control of air and spacecraft'},
  {title: 'Rimwise', percent: '10%', cost: 1, pre: [], descrip: ' Outer rim colonies and seedy parts of the galaxy'},
  {title: 'Scavenging', percent: '10%', cost: 1, pre: [], descrip: ' Searching discarded waste for useful items'},
  {title: 'Theology', percent: '10%', cost: 1, pre: [], descrip: ' Study of religion'},
  {title: 'Zero-G', percent: '10%', cost: 1, pre: [], descrip: ' Working in a vaccuum, vaccsuits, etc'},
  {title: 'Asteroid Mining', percent: '15%', cost: 2, pre: ['geology', 'zero-g', 'scavenging', 'heavy machinery'], descrip: ' Training in the tools and procedures used in mining asteroids'},
  {title: 'Astrogation', percent: '15%', cost: 2, pre: ['pioloting'] , descrip: ' Navigation in outer space'},
  {title: 'Botany', percent: '15%', cost: 2, pre: ['hydroponics'] , descrip: ' The study of plant life'},
  {title: 'Close-Quarters Combat', percent: '15%', cost: 2, pre: ['military training', 'rimwise', 'athletics'], descrip: ' Hand-to-hand, melee fighting'},
  {title: 'Engineering', percent: '15%', cost: 2, pre: ['heavy machinery', 'mechanical repair', 'computers'], descrip: ' Design, building, and use of engines, machines, and structures'},
  {title: 'Explosives', percent: '15%', cost: 2, pre: ['military training', 'chemistry'] , descrip: ' Bombs and incendiary devices'},
  {title: 'Firearms', percent: '15%', cost: 2, pre: ['military training', 'rimwise'] , descrip: ' Guns and their use'},
  {title: 'Genetics', percent: '15%', cost: 2, pre: ['biology'] , descrip: ' Heredity and the variation of inherited characteristics'},
  {title: 'Gunnery', percent: '15%', cost: 2, pre: ['military training'] , descrip: ' Starship weaponry'},
  {title: 'Hacking', percent: '15%', cost: 2, pre: ['computers'] , descrip: ' Unauthorized access to computer systems'},
  {title: 'Jury-Rigging', percent: '15%', cost: 2, pre: ['scavenging', 'mechanical repair'] , descrip: ' Makeshift repairs'},
  {title: 'Mysticism', percent: '15%', cost: 2, pre: ['art', 'archaeology', 'theology'] , descrip: ' Spiritual apprehension of hidden knowledge'},
  {title: 'Pathology', percent: '15%', cost: 2, pre: ['first aid'] , descrip: ' Study of the cause and effect of disease'},
  {title: 'Physics', percent: '15%', cost: 2, pre: ['mathematics'] , descrip: ' Study of nature and properties of matter and energy'},
  {title: 'Planetology', percent: '15%', cost: 2, pre: ['geology'] , descrip: ' Study of planets and other celestial bodies'},
  {title: 'Psychology', percent: '15%', cost: 2, pre: ['biology'] , descrip: ' The study of behavior and the human mind'},
  {title: 'Tactics', percent: '15%', cost: 2, pre: ['military training'] , descrip: ' Manuevering millitary forces in battle'},
  {title: 'Vehicle Specialization', percent: '15%', cost: 2, pre: ['mechanical repair', 'driving', 'piloting'] , descrip: ' Specific vehicle classes'},
  {title: 'Artificial Intelligence', percent: '20%', cost: 3, pre: ['engineering', 'hacking'] , descrip: ' Knowledge of simulacrum of human consciousness'},
  {title: 'Command', percent: '20%', cost: 3, pre: ['vehicle specialization', 'tactics'] , descrip: ' Leadership and authority'},
  {title: 'Cybernetics', percent: '20%', cost: 3, pre: ['jury-rigging', 'engineering'] , descrip: ' Interface between man and machine'},
  {title: 'Hyperspace', percent: '20%', cost: 3, pre: ['astrogation', 'physics', 'mysticism'] , descrip: ' Faster-than-light travel'},
  {title: 'Robotics', percent: '20%', cost: 3, pre: ['engineering'] , descrip: ' Design and operation of robots, drones, and androids'},
  {title: 'Sophontology', percent: '20%', cost: 3, pre: ['linguistics'] , descrip: ' Alien psychology'},
  {title: 'Weapon Specialization', percent: '20%', cost: 3, pre: ['gunnery', 'firearms', 'close-quarters combat', 'explosives'], descrip: ' Proficiency with a specific weapon'},
  {title: 'Xenobiology', percent: '20%', cost: 3, pre: ['genetics', 'botany', 'pathology'] , descrip: ' Alien biology'},
  {title: 'Xenoesotericism', percent: '20%', cost: 3, pre: ['mysticism'] , descrip: ' Obscure alien mysticism, religion, and belief'},
  {title: 'Surgery', percent: '20%', cost: 3, pre: ['pathology'], descrip: ' Medical speciality involving manual operation'}
];
export const ITEMS = [
  {title: 'Advanced Battle Dress        ' , descrip: 'Heavy combat outfit worn by marines in battletorn offworld engagements. It confers a <b>+15%</b> bonus to the wearer’s Armor save. It has a small exo-skeleton that allows the wearer to carry twice what they normally could.'},
  {title: 'Automed (x6)                 ' , descrip: 'Nanotech pills that assist your body in repairing damage. They give <b>+10%</b> to Body saves meant to repel disease, poison, and attempts to heal, and <b>+10%</b> to Fear saves made to reduce Stress.'},
  {title: 'Binoculars                   ' , descrip: '20x magnification. Often come with thermal and night vision options.'},
  {title: 'Bioscanner                   ' , descrip: 'Allows the user to scan the immediate area for signs of life. Generally can scan for 100m in all directions, without being blocked by most known metals. Can tell the location of signs of life, but not what that life is.'},
  {title: 'Body Cam                     ' , descrip: 'A camera worn on your clothing that can stream video back to a control center so that your other crew members can see what you’re seeing.'},
  {title: 'Camping Gear                 ' , descrip: 'Tent, Canteen, Stove, Backpack, Sleeping Bag'},
  {title: 'Cybernetic Diagnostic Scanner' , descrip: 'Allows the user to scan androids and other cybernetic organisms in order to diagnose any physical or mental issues they may be having. Often distrusted by androids. Can be used as a locating device for synthetic organisms.'},
  {title: 'Electronic Tool Set          ' , descrip: 'A full set of tools for doing detailed repair or construction work on electronics. Confers <b>+10%</b> to rolls seeking to repair electronics.'},
  {title: 'Emergency Beacon             ' , descrip: 'A small device that sends up a flare and then emits a loud beep every few seconds. Additionally, sends out a call on all radio channels to ships, or vehicles in the area. Can be configured to be silent, or to only make calls on known channels.'},
  {title: 'Field Recorder               ' , descrip: 'Used to research alien flora and fauna in the field. Can take vital signs, DNA samples, and perform basic genetic and material analysis on foreign objects.'},
  {title: 'First Aid Kit                ' , descrip: 'When used adds <b>+10%</b> to rolls made to bandage wounds and stop bleeding.'},
  {title: 'Flashlight                   ' , descrip: 'Handheld or shoulder mounted, illuminates 20m ahead of the user.'},
  {title: 'Hazard Suit                  ' , descrip: 'A standard suit for scientists to wear on alien planets. Not built for outerspace travel like the vaccsuit, but does provide air filtration and a small supply of air as well as <b>+5%</b> Armor save.'},
  {title: 'Heads-Up Display             ' , descrip: 'Often worn by marines, the HUD allows the wearer to see through the body cams of others in their unit, and tap into their guns’ smart-link capabilities.'},
  {title: 'Infrared Goggles             ' , descrip: 'Allows the wearer to see heat signatures, sometimes several hours old.'},
  {title: 'Locator                      ' , descrip: 'When worn, allows crew members at a control center (or on the bridge of a ship) to track the location of the wearer.'},
  {title: 'Lockpick Set                 ' , descrip: 'A highly advanced set of tools meant for hacking basic airlock and electronic door systems. Confers <b>+10%</b> on rolls made to open these doors.'},
  {title: 'Long-range Comms             ' , descrip: 'For use in ship-to-surface comunication.'},
  {title: 'Mag-Boots                    ' , descrip: 'Grants a magnetic grip to the wearer, allowing them to easily to walk on the surface of a ship (in space, while docked or free-floating), or metal based asteroids.'},
  {title: 'Medscanner                   ' , descrip: 'Allows the user to scan a living or dead body and to analyze it for disease or abnormalities, without having to do a biopsy (or autopsy).'},
  {title: 'MRE (x7)                     ' , descrip: '“Meals, Ready-to-Eat.” Self-contained, individual field rations in lightweight packaging. Each one has sufficient sustenance for a single person for one day (does not include water).'},
  {title: 'Oxygen Tank                  ' , descrip: 'When attached to a vaccsuit allows up to 12 hours of oxygen under normal circumstances. 4 hours under stressful circumstances. Explosive.'},
  {title: 'Pain Pills (x6)              ' , descrip: 'When ingested immediately heals 1d10 points of damage and lowers Stress by 1. There is a danger of addiction and/or overdose if used frequently.'},
  {title: 'Radio Jammer                 ' , descrip: 'When activated, renders incomprehensible the radio signals of all within 100km.'},
  {title: 'Rebreather                   ' , descrip: 'When worn, filters air and allows for underwater breathing for up to twenty minutes at a time without resurfacing.'},
  {title: 'Scalpel                      ' , descrip: 'Grants <b>+10%</b> to anyone making Surgery skill rolls. Can be used as a weapon.'},
  {title: 'Short-range Comms            ' , descrip: 'Allows communication from ship-to-ship within a reasonable distance, as well as surface-to-surface within a dozen kilometers.'},
  {title: 'Standard Battle Dress        ' , descrip: 'This light plated armor is the standard dress for marines going into combat and confers a <b>+10%</b> bonus to the wearer’s Armor save.'},
  {title: 'Standard Crew Attire         ' , descrip: 'Coveralls, leather jackets, sneakers, tank top or ragged tee. The standard outfit worn by crew members aboard spacecraft. Standard assumed attire for all classes.'},
  {title: 'Stimpak (x6)                 ' , descrip: 'Grants an immediate 2d10 to Health and temporarily increases Strength and Combat by 2d10 each for 1d10 hours. There is a danger of addiction and/or overdose if used frequently.'},
  {title: 'Survey Kit                   ' , descrip: 'When used on the surface of a planet, allows for quick mapping of a nearby few kilometers, as well as data on air breathability, gravity, and other important notable features of the surrounding landscape.'},
  {title: 'Vaccsuit                     ' , descrip: 'Allows for movement in space without suffering penalties from radiation or lack of oxygen. Requires an oxygen tank to breathe. Often used with Mag-boots and a rigging gun. Confers <b>+7%</b> to Armor saves.'},
  {title: 'Water Filter                 ' , descrip: 'Can pump 50 liters of filtered water an hour from even the most brackish swamps.'},
  {title: 'Combat Shotgun', dmg: '2d10        ', crit: 'Knockdown             ', range: '10m 20m 30m  ', ammo: 'Knockback on hit. 1/2 damage at medium range. 1/4 damage at long range.              ', shots: '4   ', special:      'Audio rangefinder: Beeps when non-friendlies approach within 10m.'},
  {title: 'Crowbar       ', dmg: '1d10        ', crit: '                      ', range: 'CQC Only     ', ammo: '                                                                                  ', shots: '', special:      '+5 (Mechanical Repair). Confers Advantage on Strength checks to open jammed airlocks, or lift heavy objects.'},
  {title: 'Flame Thrower ', dmg: '<u>2d10</u>', crit: '                      ', range: '2m 10m 20m   ', ammo: '                                                                                     ', shots: '8   ', special:      'Body save or get set on fire and take <u>1d10</u> dmg. per turn.'},
  {title: 'Flare Gun     ', dmg: '1d10        ', crit: '                      ', range: '5m 10m 20m   ', ammo: 'High-intensity flare: Visible from 25km away.                                        ', shots: '2   ', special: ''},
  {title: 'Foam Gun      ', dmg: 'N/A         ', crit: 'No save               ', range: '<1m 5m 10m   ', ammo: 'Quick-hardening foam: Body/instinct save to avoid or become stuck. Foam coveres 5sqm.', shots: '10'  , special:      'Fire retardant.'},
  {title: 'Frag Grenade (x6)  ', dmg: '<u>1d10</u>', crit: '                      ', range: '20m 30m 40m  ', ammo: 'Deals damage to all within a 15m radius.                                             ', shots: '1   ', special:      'Can often do 1MDMG to a ship if placed in their engine room or bridge.'},
  {title: 'Hand Welder   ', dmg: '1d10        ', crit: '                      ', range: 'CQC Only     ', ammo: '                                                                                     ', shots: '∞   ', special:      'Ultra heat emitter: Cuts through airlocks/heavy doors. -10 vs. Armor Save'},
  {title: 'Laser Cutter  ', dmg: '1d% or 1MDMG', crit: '                      ', range: '25m 250m 700m', ammo: 'Takes 1 round to re-charge between shots.                                            ', shots: '6   ', special:      'Takes 1 hour to re-charge from a power source, or 6 hours in sunlight.'},
  {title: 'Nail Gun      ', dmg: '2d10        ', crit: 'Double damage         ', range: '<1m 5m 10m   ', ammo: 'Heavy Duty Nails: -10 vs. Armor Save                                                 ', shots: '32  ', special:   ''},
  {title: 'Pulse Rifle   ', dmg: '5d10        ', crit: 'Double damage         ', range: '15m 125m 300m', ammo: 'Phosphorus Rounds. Fully automatic.                                                  ', shots: '1(3)', special:      'Smart-link system: +5 (Combat if wearing HUD). Pump-Action Grenade Launcher: Holds 6 frag grenades.'},
  {title: 'Revolver      ', dmg: '3d10        ', crit: 'Knockdown             ', range: '2m 30m 125m  ', ammo: 'Kineti-slugs: -5 vs. Armor Save.                                                     ', shots: '8   ', special:   ''},
  {title: 'Rigging Gun   ', dmg: '2d10        ', crit: 'Impale. Triple damage.', range: '10m 30m 100m ', ammo: 'Micro-filament: 500m. Hard to cut.                                                   ', shots: '1   ', special:      'Retractable Harpoon: Body/Instinct save or become entangled. Does an extra +<u>1d10</u> damage when grapnel is pulled out of target.'},
  {title: 'Scalpel       ', dmg: '1d10        ', crit: '+1d10 DMG and bleeding', range: 'CQC Only     ', ammo: '                                                                                  ', shots: '', special:      '+10 (Surgery)'},
  {title: 'Smart Rifle   ', dmg: '<u>1d10</u>', crit: 'x3 DMG                ', range: '25m 200m 500m', ammo: 'Armor Piercing: -10 vs. Armor Save                                                   ', shots: '12  ', special:      'Smart-link system: +10 (Combat if wearing HUD). Spectroscope: Night/Thermal Vision'},
  {title: 'SMG           ', dmg: '4d10        ', crit: '                      ', range: '10m 75m 150m ', ammo: 'Fully automatic.                                                                     ', shots: '1(5)', special:   ''},
  {title: 'Stun Baton    ', dmg: '1d10        ', crit: 'No save               ', range: 'CQC Only     ', ammo: '                                                                                  ', shots: '', special:      'Body save or be stunned for 1 round.'},
  {title: 'Tranq Pistol  ', dmg: 'N/A         ', crit: 'No save               ', range: '2m 10m 20m   ', ammo: 'Tranq Darts                                                                          ', shots: '6   ', special:      'Body[+] save or fall unconscious for 1d10 rounds.'},
  {title: 'Vibechete     ', dmg: '2d10        ', crit: 'Hack off limb         ', range: 'CQC Only     ', ammo: '                                                                                     ', shots: '    ', special:      'Can hack through limbs, or dense forestry, but not metal doors, airlocks, etc.'},
];

export const STRESS_PANIC = [
  {
    title: 'teamster',
    fear: 'Once per session, a Teamster may re-roll a a roll on the Panic Effect Table'
  },
  {
    title: 'scientist',
    fear: 'Whenever a Scientist fails a Sanity Save, every friendly player nearby gains 1 Stress'
  },
  {
    title: 'android',
    fear: 'Fears Saves made in the presence of Android have Disadvantage'
  },
  {
    title: 'marine',
    fear: 'Whenever a Marine Panics, every friendly player nearby must make a Fear Save',
    extra: 'Gain +5 COMBAT whenever a friendly Marine is nearby'
  }
];

export const DERELICT = [
  {
    title: 'ship class',
    table:
    [
      ...Array(35).fill('mining frigate'),
      ...Array(23).fill('freighter'),
      ...Array(14).fill('shuttle'),
      ...Array(9).fill('courier'),
      ...Array(4).fill('research vessel'),
      ...Array(4).fill('blockade runner'),
      ...Array(3).fill('cutter'),
      ...Array(4).fill('troopship'),
      ...Array(4).fill('colony ship')
    ],
  },
  {
    title: 'habitation status',
    table: [
      ...Array(85).fill('uninhabitable'),
      ...Array(10).fill('habitable (non-functioning)'),
      ...Array(5).fill('habitable (functioning)')
    ],
  },
  {
    title: 'survivors',
    table: [
      ...Array(90).fill('no survivors'),
      ...Array(6).fill('2d10 survivors (in cryosleep)'),
      ...Array(4).fill('survivors')
    ],

  },
  {
    title: 'engine status',
    table: [
      ...Array(81).fill('Engine, Thrusters, Jump Drive non-functioning'),
      ...Array(13).fill('Stable Engine, Thrusters, Jump Drive'),
      ...Array(6).fill('Unstable Core')
    ],
  },
  {
    title: 'salvage_1',
    table:  [
      ...Array(50).fill('2d100 units of scrap'),
      ...Array(26).fill('1d10 fuel unit(s)'),
      ...Array(6).fill('2d10 units of galley stock'),
      ...Array(4).fill('1d10 cryopods'),
      ...Array(3).fill('medbay'),
      ...Array(3).fill('weapon'),
      ...Array(4).fill('computer'),
      ...Array(4).fill('jump drive')
    ],
  },
  {
    title: 'salvage_2',
    table:  [
      ...Array(61).fill('4d10 units of ore'),
      ...Array(15).fill('3d10 units metal'),
      ...Array(10).fill('1d100 trade units of random cargo'),
      ...Array(7).fill('1d10 units of precious metal'),
      ...Array(7).fill('1d10 units of contraband')
    ],
  },
  {
    title: 'cause of ruination',
    table:   [
      'Virus',
      ...Array(9).fill('Combat'),
      ...Array(10).fill('Raided by Pirates'),
      ...Array(5).fill('Hyperspace Malfunction'),
      ...Array(5).fill('Abandoned Ship'),
      ...Array(5).fill('Insane AI                        '),
      ...Array(5).fill('Mutiny                           '),
      ...Array(5).fill('Crash: Other Ship                '),
      ...Array(5).fill('Crash: Space Debris              '),
      ...Array(5).fill('Crash: Jump Drive Miscalculation '),
      ...Array(3).fill('Engine Failure                   '),
      ...Array(3).fill('Cannibalism                      '),
      ...Array(3).fill('Nerve Gas                        '),
      ...Array(3).fill('Escape Pod Never Returned        '),
      ...Array(3).fill('Betrayal/Backstabbing            '),
      ...Array(2).fill('Succumbed to Nightmares          '),
      ...Array(2).fill('Hatch Opened, No Air             '),
      ...Array(2).fill('Cargo Created Mishap             '),
      ...Array(2).fill('Starvation                       '),
      ...Array(2).fill('Part of a Conspiracy             '),
      'Thrusters Slagged                ',
      'Weapons System Malfunction       ',
      'Cryosleep Never Disengaged       ',
      'Complex Series of Events         ',
      'Suicide Pact                     ',
      'Parasite Infestation             ',
      'Environmental Systems Failure    ',
      'Uncontrollable Fire              ',
      'Failed Fraud Attempt             ',
      'Void Worshipping                 ',
      'Bizarre Love Triangle            ',
      'Fight Spiraled Out of Control    ',
      'Chainsaw Rampage*                ',
      'Drug Addled Debauchery           ',
      'Fatal Depressurization           ',
      'Nightmares Ending in Heart Attack',
      'Mob Hit                          ',
      'Crew Members Vanished            ',
      'Prank Taken Too Far              ',
      'William Tell Trick               ',
    ],
  },
  {
    title: 'weird',
    table:   [
      'Haunted',
      ...Array(9).fill('Inhabited by Alien Life'),
      ...Array(10).fill('Terraformed by strange creatures'),
      ...Array(5).fill('Crew Dressed For Costume Party'),
      ...Array(5).fill('Crew All Identical'),
      ...Array(5).fill('Crew was preparing Theatrical Performance'),
      ...Array(5).fill('Morbid Artwork'),
      ...Array(5).fill('Pet Hoarders'),
      ...Array(5).fill('Erotic Sculptures'),
      ...Array(5).fill('Communist Regalia'),
      ...Array(3).fill('Company Uniform'),
      ...Array(3).fill('Cult Members'),
      ...Array(3).fill('Extensive Journals Kept'),
      ...Array(3).fill('Strange Health Obsession'),
      ...Array(3).fill('Unnervingly Clean'),
      ...Array(2).fill('Android was Poisoning Captain'),
      ...Array(2).fill('Ancient Ship'),
      ...Array(2).fill('Temporal Distortions'),
      ...Array(2).fill('Failed Utopia'),
      ...Array(2).fill('Crew Weighed and Measured Weekly'),
      'Extensive Body Modification',
      'Isolated Physics Anomalies',
      'Sexual Deviants',
      'Religious Extremists',
      'Transhumanist Android Worshippers',
      'Anti-Android Conspiracists',
      'Nauseating Stench',
      'Everything is Jury-Rigged',
      'Crew Taking Video Through the Catastrophe',
      'Body Horror',
      'Scooby-Doo Crew',
      'Interior Coated in Flesh, Doors are Membranes',
      'Whispering Echoes Always a Room Ahead',
      'Dolls in Macabre Tableaux',
      'Dead Crew: Exploded Heads',
      'Elaborately Posed Corpses (Hooks & Chains)',
      'Flickering Lights and Frenzied Screams',
      'Ship Rearranges Itself Frequently',
      'Ship Has Infinite Depth',
      'Fruit Basket, Greeting Card Inexplicably Addressed to Crew',
    ]
  }
];

export const SHIP_NAMES = [
  [
    'IAGO',
    'HECATE',
    'OBERON',
    'WHITEHALL',
    'DUNCAN',
    'BANQUO',
    'WINTER',
    'MARLOW',
    'TEMPEST',
    'FAUST',
  ],
  [
    'VALEFOR',
    'OPHANIM',
    'MARAX',
    'MARINER',
    'LABOLAS',
    'ASTAROTH',
    'CHERUBIM',
    'TYRANT',
    'BALAAM',
    'MURMUR',
  ],
  [
    'ECHO',
    'ALPHA',
    'OMEGA',
    'KING',
    'BEGGER',
    'DELTA',
    'EPISLON',
    'JIBRIL',
    'BRAVO',
    'TANGO',
  ]
];

export const SPACE_STATION = [
  {
    title: 'station_name1',
    table: [
      'Azreal\'s',
      'Dunmah\'s',
      'Marut\'s',
      'Gorgon\'s',
      'Soter\'s',
      'Pontian\'s',
      'Vitalin\'s',
      'Iblis\'s',
      'Al-\'Uzza\'s',
      'Vanth\'s'
    ]
  },
  {
    title: 'station_name2',
    table: [
      'Price',
      'Sorrow',
      'Redemption',
      'Revenge',
      'Ring',
      'Crown',
      'Sword',
      'Shield',
      'Cross',
      'Herald'
    ]
  },
  {
    title: 'core_station',
    table: [
      'overcrowded habitat colony',
      'palatial estate',
      'secret corporate research facility',
      'marine battle school',
      'bustling trading port',
      'sprawling megatropolis',
      'high security corporate vault',
      'semi-autonomous shipyard',
      'solitary monastary',
      'ancient jump gate'
    ]
  },
  {
    title: 'celestial_body',
    table: [
      'still terraforming planet',
      'overpopulated slumworld',
      'resource rich planet',
      'desolate planetoid',
      'white dwarf star',
      'moon of an inhabited planet',
      'unpopulated paradise world',
      'giant asteroid cluster',
      'red supergiant',
      'black hole, past event horizon'
    ]
  },
  {
    title: 'core_leader',
    table: [
      'first-colony descendent',
      'asteroid mining oligarch',
      'reclusive intellectual',
      'scheming marine general',
      'teamster union rep',
      'sadistic decadent',
      'decorated regional governor',
      'rimwar veteran commander',
      'reformed criminal outcast',
      'dynastic child-heir'
    ]
  },
  {
    title: 'group',
    table: [
      'radical colonial separatists',
      'The Valecore Mining Consortium',
      'The Exo-Credit Federated Union',
      'The 91st Colonial Dragoons',
      'Teamster\'s Local 101977L',
      'The Yamguchi-gumi Clan',
      'The Crashlander Titan 2nd Fleet',
      'The Principality of Christian XII',
      'The Decanon Caliphate',
      'The House of Tarkhan'
    ]
  },
  {
    title: 'goods',
    table: [
      'equipment',
      'asteroid ore',
      'weapons',
      'scrap metal',
      'prisoners',
      'warp cores',
      'galley stock',
      'ship parts',
      'used ships',
      'fuel'
    ]
  },
  {
    title: 'resource',
    table: [
      'android laborers',
      'asteroid mining machinery',
      'hardened mercenaries',
      'black market cybermods',
      'life-saving medicine',
      'doctors who don\'t ask questions',
      'rations',
      'out of work scientists',
      'oxygen reserves',
      'recreational drugs'
    ]
  },
  {
    title: 'crisis',
    table: [
      '<b class="magenta">Hostage Situation</b>. Command of the station has been taken by a rival faction who demand <u>1d10kcr</u> ransom.',
      '<b class="magenta">Refugee Crisis</b>. The station is overrun with refugees. Everything is 1d10 + 1x more expensive than usual.',
      '<b class="magenta">Food Shortage</b>. The station will pay 1d10 + 1kcr for food and another random resource. Theft is rampant.',
      '<b class="magenta">Quarantine</b>. After boarding the station you learn that it has been quarantined. No one is allowed to leave.',
      '<b class="magenta">Bout of Civil Unrest</b>. Rioting and looting. Mercenary death squads roam the corridors executing collaborators.',
      '<b class="magenta">Disaster</b>. Crash landing, mass explosion or sabotage. Station is on full alert and going down without repairs.',
      '<b class="magenta">General Strike</b>. Unions have organized. Protests, picket lines and intense riots. Commerce is shut down.',
      '<b class="magenta">Uncanny Abandonment</b>. The station hosts the aftermath of some bloody, haunted or mysterious happening.',
      '<b class="magenta">Martial Law Edict</b>. All ships are boarded and inspected, station visas are issued and a curfew is in effect.',
      '<b class="magenta">Blockade</b>. The station is under siege by the rival faction and access has been cut off. Your ship will be boarded.'
    ]
  },
  {
    title: 'structure',
    table: [
      '<b class="magenta">Asteroid Surface</b>. This station has been built on the outside surface of the asteroid, much the same way a building rests on the surface of a planet',
      '<b class="magenta">Asteroid Interior</b>. While there may be structures on the outside of the asteroid the majority of the station exists "underground" as a series of tunnels, caves, or similar structures',
      '<b class="magenta">Spindle</b>. A common design, shaped like a spinning top with towers rising from the top and/or bottom',
      '<b class="magenta">Cylinder</b>. The cylinder\'s rotation could provide a rationale for artificial gravity and the station could be quite large, like an O\'Neill Cylinder',
      '<b class="magenta">Sphere</b>. Can be as big as a Dyson or Bernal Sphere or as small as a single pod-station',
      '<b class="magenta">Torus/Ring</b>. The most common design. Like the Standford Torus or Bishop Ring, the outer ring could provide enough centrifugal force to provide artifical gravity',
      '<b class="magenta">Tower</b>. A station with an angular or blocky design, like a skyscraper flung into space',
      '<b class="magenta">Modular</b>. Built from discrete modules or "beads" that can be removed or added on to',
      '<b class="magenta">Platform</b>. Design based on a large ship with clearly defined levels/decks',
      '<b class="magenta">Amalgamation</b>.'
    ]
  },
  {
    title: 'common_problems',
    table: [
      '<b class="magenta">No Artificial Gravity</b>. Zero-G Skill Check for complex maneuvers',
      '<b class="magenta">Resource Scarcity</b>. Food, water, oxygen, shelter is hard to find',
      '<b class="magenta">Trade Good Scarcity</b>. Lack of fuel, warp cores, ammunition',
      '<b class="magenta">Oxygen Poor</b>. Strenuous activities at [-]. O2 taxation',
      '<b class="magenta">Non-standard Day/Night Cycle</b>. Resting at [-]',
      '<b class="magenta">Poor Water Treatment Facilities</b>. Healing at [-]',
      '<b class="magenta">Low Security</b>. High risk of theft, threat of violence, piracy, etc',
      '<b class="magenta">High Secuirty</b>. High risk of authoritarian police, taxation, prison, etc.',
      '<b class="magenta">Xenophobic Population</b>. Suspicious/hostile to stranger/outsiders',
      '<b class="magenta">Poor Maintenance</b>. Minimum Stress +1. Resting and Healing at [-]. High risk of damage to the station during combat',
    ]
  },
  {
    title: 'noteworthy_locations',
    table: [
      ...Array(3).fill('repair'),
      'port',
      'colony',
      'military',
      'mining',
      'corporate',
      'prison',
      'religious'
    ],
    location_descrip: {
      repair: [
        ...Array(5).fill('dry dock'),
        ...Array(5).fill('vehicle repair'),
        ...Array(5).fill('chop shop'),
        ...Array(5).fill('bars'),
        ...Array(5).fill('showers'),
        ...Array(5).fill('capsule motel'),
        ...Array(5).fill('navigation library'),
        ...Array(5).fill('warp core storage'),
        ...Array(5).fill('teamster union hall'),
        ...Array(5).fill('military lounge'),
        ...Array(5).fill('commercial travel'),
        ...Array(5).fill('private hanger'),
        ...Array(5).fill('showers'),
        ...Array(5).fill('metal foundry'),
        ...Array(5).fill('Ore Trade/Refinery'),
        ...Array(5).fill('food court'),
        ...Array(5).fill('Fuel Bay/Warp Cores'),
        ...Array(5).fill('slickscreens'),
        'red light district',
        'black market',
        'tiny chapel',
        'weapons fabrication',
        'advanced r&d',
        'experimental ftl lab',
        'astronavigator terminals',
        'station overseer',
        'holding cells',
        'power station'
      ],
      port: [
        ...Array(5).fill('food stand'),
        ...Array(5).fill('dry dock'),
        ...Array(5).fill('fence for stolen goods'),
        ...Array(5).fill('black market'),
        ...Array(5).fill('re-sleeving facility'),
        ...Array(5).fill('cybermod shop'),
        ...Array(5).fill('imports warehouse'),
        ...Array(5).fill('designer drugs'),
        ...Array(5).fill('gene therapy'),
        ...Array(5).fill('holotat shop'),
        ...Array(5).fill('glass blower'),
        ...Array(5).fill('technobladesmith'),
        ...Array(5).fill('slaughter yard'),
        ...Array(5).fill('fabric loom'),
        ...Array(5).fill('sweatshop'),
        ...Array(5).fill('gambling house'),
        ...Array(5).fill('dance club'),
        ...Array(5).fill('teamster bar'),
        'cassette library',
        'specimens & oddities',
        'red light district',
        'military black site',
        'navigator guildhouse',
        'decorative rugs',
        'tea shop',
        'old earth antique shop',
        'custom androids',
        'ship designer'
      ],
      colony: [
        ...Array(5).fill('Farming Unit              '),
        ...Array(5).fill('Food Court                '),
        ...Array(5).fill('Slickscreen               '),
        ...Array(5).fill('Bar/Club                  '),
        ...Array(5).fill('Slaughterhouse            '),
        ...Array(5).fill('Seed/Gene Storage         '),
        ...Array(5).fill('Sleeping Units            '),
        ...Array(5).fill('Meeting                   '),
        ...Array(5).fill('Aquaponics Tanks          '),
        ...Array(5).fill('Markets                   '),
        ...Array(5).fill('School/Training Facilities'),
        ...Array(5).fill('Library/Research Lab      '),
        ...Array(5).fill('Upscale Housing           '),
        ...Array(5).fill('Security Outpost          '),
        ...Array(5).fill('Clinic                    '),
        ...Array(5).fill('Factory                   '),
        ...Array(5).fill('Greenhouse                '),
        ...Array(5).fill('Turret Emplacement        '),
        'Red Light District        ',
        'Brig                      ',
        'Power Station             ',
        'Pharmalab                 ',
        'Governor’s Mansion        ',
        'Armory                    ',
        'Temple                    ',
        'Courthouse/Records        ',
        'Landing Strip             ',
        'Communication Array       ',
      ],
      military: [
        ...Array(5).fill('Admin Offices'),
        ...Array(5).fill('Drop Station'),
        ...Array(5).fill('Training Rooms'),
        ...Array(5).fill('Shooting Range'),
        ...Array(5).fill('Command Center'),
        ...Array(5).fill('Defensive Weaponry'),
        ...Array(5).fill('Vehicle Repair Center'),
        ...Array(5).fill('Square Brig'),
        ...Array(5).fill('Troopship Carrier'),
        ...Array(5).fill('Barracks'),
        ...Array(5).fill('Interrogation Rooms'),
        ...Array(5).fill('Medbay'),
        ...Array(5).fill('R&D Department'),
        ...Array(5).fill('Drop-tank Hangar'),
        ...Array(5).fill('Mess Hall'),
        ...Array(5).fill('Officer’s Lounge'),
        ...Array(5).fill('“Off-base” Housing'),
        ...Array(5).fill('Master Computer'),
        'Diplomatic Embassy',
        'Officer’s Quarters',
        'Weapon Testing',
        'Fighter Squadron',
        'Ammunition Storage',
        'Re-Sleeving Facility',
        'Cryochambers',
        'Intelligence Facility',
        'Exomech Hangar',
        'Massive Weapon',
      ],
      mining: [
        ...Array(5).fill('Material Processing    '),
        ...Array(5).fill('Shipping Warehouse     '),
        ...Array(5).fill('Storage Warehouse      '),
        ...Array(5).fill('Dry Dock               '),
        ...Array(5).fill('Assembly Line          '),
        ...Array(5).fill('Metal Refinery         '),
        ...Array(5).fill('Air Scrubber           '),
        ...Array(5).fill('Water Reclamation      '),
        ...Array(5).fill('Sleeping Pods          '),
        ...Array(5).fill('Cafeteria              '),
        ...Array(5).fill('Showers/Soakers        '),
        ...Array(5).fill('Corp. Conference Room  '),
        ...Array(5).fill('Garage/Hangar          '),
        ...Array(5).fill('Geology Lab            '),
        ...Array(5).fill('Records/Maps/Blueprints'),
        ...Array(5).fill('Slickscreen            '),
        ...Array(5).fill('Fighting Ring          '),
        ...Array(5).fill('Android Maintenance    '),
        'Conjugal Trailers      ',
        'Xenobio Lab            ',
        'Extraction Point       ',
        'Infraction Cells       ',
        'Cloning Facility       ',
        'Communications         ',
        'Exosuit Hangar/Repair  ',
        'Life Support           ',
        'Laser Drilling Array   ',
        'Company Store          ',
      ],
      corporate: [
        ...Array(5).fill('Offices                 '),
        ...Array(5).fill('Open Floor Plan Office  '),
        ...Array(5).fill('Cubicles                '),
        ...Array(5).fill('Testing Lab             '),
        ...Array(5).fill('AI Computer Banks       '),
        ...Array(5).fill('Labratory               '),
        ...Array(5).fill('Quarantine Room         '),
        ...Array(5).fill('Data Analysis Office    '),
        ...Array(5).fill('Android Storage         '),
        ...Array(5).fill('Warehouse               '),
        ...Array(5).fill('Shipping & Receiving    '),
        ...Array(5).fill('Mail Rooms              '),
        ...Array(5).fill('Meeting Rooms           '),
        ...Array(5).fill('Clean Room              '),
        ...Array(5).fill('Employee Housing        '),
        ...Array(5).fill('Hazardous Materials     '),
        ...Array(5).fill('Cryostorage             '),
        ...Array(5).fill('Containment Lab         '),
        'Private Offices         ',
        'Luxurious Boardroom     ',
        'High Security Vault     ',
        'Illegal DNA Splicing Lab',
        'Embryonic Storage       ',
        'Morgue                  ',
        'Animal Testing Pens     ',
        'Killteam Barracks       ',
        'Experiment #237         ',
        'Mega-AI Brain           ',
      ],
      prison: [
        ...Array(5).fill('Ruined Cellblock      '),
        ...Array(5).fill('Administration Offices'),
        ...Array(5).fill('Morgue                '),
        ...Array(5).fill('Riot Armory           '),
        ...Array(5).fill('Guard Quarters        '),
        ...Array(5).fill('High Security Area    '),
        ...Array(5).fill('Isolation Chambers    '),
        ...Array(5).fill('Cryostorage'),
        ...Array(5).fill('VR Exercise Yard      '),
        ...Array(5).fill('Prison Cells          '),
        ...Array(5).fill('Group Dormitory       '),
        ...Array(5).fill('Quarantine Unit       '),
        ...Array(5).fill('Solitary Confinement  '),
        ...Array(5).fill('Canteen               '),
        ...Array(5).fill('Gruel Kitchen         '),
        ...Array(5).fill('Labor Camp            '),
        ...Array(5).fill('Execution Chambers    '),
        ...Array(5).fill('Scrap Metal Workshop  '),
        'Slickscreen Classrooms',
        'Illegal Human Testing ',
        'Mind Wipe Lab         ',
        'Mass Grave            ',
        'Reprograming Facility ',
        'Military Black Site   ',
        'AI Prison Server      ',
        'Android Scrapyard     ',
        'Comissary             ',
        'Crematorium           ',
      ],
      religious: [
        ...Array(5).fill('Prayer Gardens'),
        ...Array(5).fill('Observatory'),
        ...Array(5).fill('Cellarium'),
        ...Array(5).fill('Chapter House'),
        ...Array(5).fill('Dorter'),
        ...Array(5).fill('Refectory'),
        ...Array(5).fill('Infirmiry'),
        ...Array(5).fill('Kitchens'),
        ...Array(5).fill('Lavatorium'),
        ...Array(5).fill('Misericord'),
        ...Array(5).fill('Scriptorium'),
        ...Array(5).fill('Calefactory'),
        ...Array(5).fill('Musalla'),
        ...Array(5).fill('Minaret'),
        ...Array(5).fill('Prayer Hall'),
        ...Array(5).fill('Ablution Fountains'),
        ...Array(5).fill('Chinjusha'),
        ...Array(5).fill('Three Gate'),
        'Bell Tower',
        'Shrine',
        'Lecture Hall',
        'Grand Reliquary',
        'Massive Statue',
        'Secret Chambers',
        'Palatial Gardens',
        'Scourging Room',
        'Bishop’s Manor',
        'Unmarked Prison Cell',
      ]
    }
  },
  {
    title: 'rim_landmarks',
    table: [
      'Heavily Guarded Corporate DMZ  ',
      'Battered Asteroid Field        ',
      'Uninhabitable Desert Planet    ',
      'Strip-Mined Ice World          ',
      'First Generation Pioneer Colony',
      'Resource Rich Asteroid Cluster ',
      'The Disputed Territory Border  ',
      'Massive Jump-5 Derelict Hulk   ',
      'Burgeoning Off‑World Colony    ',
      'Ship Graveyard',
    ]
  },
  {
    title: 'rim_station',
    table: [
      'Independent Colony ',
      'Run Down Factory   ',
      'Military Base      ',
      'Lighthouse         ',
      'Asteroid Mining    ',
      'Maximum Sec. Prison',
      'Scrap Processing   ',
      'Rest & Refuel      ',
      'Black Market       ',
      'Abandoned Derelict ',
    ]
  },
  {
    title: 'call_sign',
    table: [
      'Remote Site-[d100]-[Letter]',
      '[d100]-[d10]',
      'Forward Base-[d10]-[Letter]',
      'Rimward-Post [d10]-[d10]',
      '[Letter]-[d100]',
      'Supervisor-[Letter]-[d10]',
      'Control-[d100]',
      'Command-[d10]-[d10]',
      'Outpost [d100]-[Letter]-[d10]',
      'Bridle-[d10]',
    ]
  },
  {
    title: 'control_faction',
    table: [
      'The Anders-Klimt Mining Corporation   ',
      'The Gaff Android Labor Syndicate      ',
      'The 601st Colonial Marine Regiment    ',
      'Salo-Mercury Biomotors Inc.           ',
      'The Apostles Gate Church              ',
      'Confederated Systems Inc.             ',
      'The “Opera” Fleet of Mercenary Raiders',
      'The Sindec Alloyed Metals Corporation ',
      'SEBACO Mining Ltd.                    ',
      'The Limited Colonial Government     ',
    ]
  },
  {
    title: 'rival_faction',
    table: [
      'The Synthetic Liberation Front',
      'Altruistic Scientists         ',
      'Neo-Haram Anarchists          ',
      'Violent Return‑Earthers       ',
      'Carter Tactical Concerns Ltd. ',
      'Armadyne Weapons, Inc.        ',
      'House Sivaranjan              ',
      'Secret Union Instigators      ',
      'Black Dawn Mercenaries        ',
      'The Family of Eleven          ',
    ]
  },
  {
    title: 'rival_leader',
    table: [
      'Renegade Android',
      'Powerful Rogue AI',
      'Ruthless Criminal Despot',
      'Charismatic Revivalist',
      'Perverse Corp. Warden',
      'Highly Intelligent Merc. Captain',
      'Cunning Corporate Spy',
      'Merciless Slaver',
      'Stalwart Union Organizer',
      'Relentless Warrant Officer',
    ]
  }
];

export const CLASSES = ['TEAMSTER', 'ANDROID', 'SCIENTIST', 'MARINE'];
